spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/shortener}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVICE_PORT:8080}